const {
  REACT_APP_API_URL,
  REACT_APP_BASIC_KEY,
  REACT_APP_USER_COOKIE,
  REACT_APP_IMAGEKIT_URL,
  REACT_APP_IMAGEKIT_PUBLIC_KEY,
  REACT_APP_IMAGEKIT_AUTH_URL,
  REACT_APP_CLOUD_NAME,
  REACT_APP_CLOUD_URL,
  REACT_APP_UPLOAD_PRESET,
} = process.env;

const config = {
  basicKey: REACT_APP_BASIC_KEY,
  apiUrl: REACT_APP_API_URL,
  userCookie: REACT_APP_USER_COOKIE,
  cloudName: REACT_APP_CLOUD_NAME,
  cloudURL: REACT_APP_CLOUD_URL,
  uploadPreset: REACT_APP_UPLOAD_PRESET,
  imagekitUrl: REACT_APP_IMAGEKIT_URL,
  imagekitPublicKey: REACT_APP_IMAGEKIT_PUBLIC_KEY,
  imagekitAuthUrl: REACT_APP_IMAGEKIT_AUTH_URL,
};

export default config;
