name: to set environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_BASIC_KEY: ${{ secrets.REACT_APP_BASIC_KEY }}
          REACT_APP_IMAGEKIT_AUTH_URL: ${{ secrets.REACT_APP_IMAGEKIT_AUTH_URL }}
          REACT_APP_IMAGEKIT_PUBLIC_KEY: ${{ secrets.REACT_APP_IMAGEKIT_PUBLIC_KEY }}
          REACT_APP_IMAGEKIT_URL: ${{ secrets.REACT_APP_IMAGEKIT_URL }}
          REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
          REACT_APP_USER_COOKIE: ${{ secrets.REACT_APP_USER_COOKIE }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: build
